[package]
name = "platform-mac"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rt-utils.workspace = true
engine.workspace = true
libc.workspace = true
mach2.workspace = true
core-foundation.workspace = true
core-foundation-sys.workspace = true
log.workspace = true
thiserror.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
coreaudio-sys = "0.2"
objc2.workspace = true
objc2-foundation.workspace = true

[lib]
name = "platform_mac"
