[package]
name = "vst3-host"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
log.workspace = true
libc.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-foundation = { workspace = true, features = ["NSString", "NSData"] }
